export const ADD_SHOPPING_LIST = 'ADD_SHOPPING_LIST';
export const EDIT_SHOPPING_LIST = 'EDIT_SHOPPING_LIST';
export const DELETE_SHOPPING_LIST = 'DELETE_SHOPPING_LIST';
export const ARCHIVE_SHOPPING_LIST = 'ARCHIVE_SHOPPING_LIST';
export const ACTIVATE_SHOPPING_LIST = 'ACTIVATE_SHOPPING_LIST';
export const SELECT_SHOPPING_LIST = 'SELECT_SHOPPING_LIST';

export const RECOVER_SHOPPING_LISTS = 'RECOVER_SHOPPING_LISTS';
export const REMOVE_ALL_LISTS = 'REMOVE_ALL_LISTS';

export const BUY_ITEM = 'BUY_ITEM';
export const RETURN_ITEM = 'RETURN_ITEM';
